sonar.projectKey=AlbernazBR_Email
sonar.organization=albernazbr
sonar.projectName=Email Spam Filter
sonar.projectVersion=1.0

sonar.host.url=https://sonarcloud.io
sonar.sourceEncoding=UTF-8

# Código fonte
sonar.sources=src

# Testes
sonar.tests=tests

# Exclusões
sonar.exclusions=**/bin/**,**/obj/**,**/tools/**
sonar.coverage.exclusions=**/tests/**,**/tools/**

# Cobertura de testes (gerado pelo coverlet)
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
